# Aulas de Redes Neurais

- https://www.youtube.com/watch?v=qoAB5z23lQk

In [8]:
import tensorflow as tf
import numpy as np

In [9]:
tf.__version__

'2.4.1'

# Definindo uma constante

In [10]:
# Definido uma constante no TensorFlow
tensor = tf.constant([[23,4],[32,51]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [16]:
# Acessando as dimensões de um tensor
tensor.shape

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>>

In [17]:
# Acessando os valores de um tensor com o numpy sem precisar de uma seção
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [18]:
# Podemos converter um numpy array para um tensor do TensorFlow
numpy_array = np.array([[30, 20],[10, 45]])
numpy_array

array([[30, 20],
       [10, 45]])

In [19]:
# Se uma sessão não for inicializada, não podemos acessar os valores da constante
tensor_from_np = tf.constant(numpy_array)
tensor_from_np

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[30, 20],
       [10, 45]])>

# Definindo uma variável

In [5]:
import time
for i in range(10):
    print('Iteration', i, 'Score:', i**2, end='')
    time.sleep(i)
    print('', end='\r')

In [20]:
# Definindo uma variável

variable = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [21]:
# Acessando o valor de uma variável
variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [22]:
# Alterando um valor específico de uma variável
variable[0,2].assign(100)
variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

# Operação com tensores

In [23]:
# Definindo o tensor
tensor2 = tf.constant([[1,2],[3,4]])
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [26]:
# Adição de um tensor com um escalar
tensor2+2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [27]:
# Mutiplicação de um tensor por um escalar
tensor2*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

## Funções do numpy com tensores

In [28]:
# Elevando ao quadrado
np.square(tensor2)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [29]:
# Raiz quadrada
np.sqrt(tensor2)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [30]:
# Seno
np.sin(tensor2)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [33]:
# Produto escalar
tensor3=tf.constant([[1,0],[0,1]])

np.dot(tensor2,tensor3)

array([[1, 2],
       [3, 4]], dtype=int32)

# Strings

In [35]:
tf_string = tf.constant('Tensorflow')
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

## Operações com string

In [41]:
# Definir tamanho
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [43]:
# Definir decodificação

tf.strings.unicode_decode(tf_string,'UTF8')

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

## Armazenando arrays (vetores) de strings

In [51]:
# Definindo o array de strings
tf_string_array = tf.constant(["TensorFlow","Deep Learning","AI"])

# Imprimindo os parâmetros encontrados
for string in tf_string_array:
    print(string.numpy())
    print('Len:',tf.strings.length(string).numpy())
    print('Code:',tf.strings.unicode_decode(string,'UTF8').numpy())
    print()

b'TensorFlow'
Len: 10
Code: [ 84 101 110 115 111 114  70 108 111 119]

b'Deep Learning'
Len: 13
Code: [ 68 101 101 112  32  76 101  97 114 110 105 110 103]

b'AI'
Len: 2
Code: [65 73]

